spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        stdio: true
        type: SYNC
        name: eric-jarvasian-pexel-image-mcp
        version: 0.0.1


